### PR TITLE
add language identifier to README.md

### PR DESCRIPTION
**Pull request by eponymz**
Additionally add in information + example usage snippets for copy/paste directly into vscode.

### CODE REVIEW

**Comment by denco** [comment]
Hi, it's not so good idea to overwrite a standard markdown file extensions (`.md`)  for using it with confluence plugin.

You can do it personally, but in common it's not so usefull.

Additionally confluence plugin register 3 file extensions: `.confluence`, `.wiki` and `.markup` 

IMHO it's would better to use registered file extensions instead of overwriting other.

**Comment by eponymz** [comment]
I see what you are saying now.. the first example that i added. Got it. Will take that out, it makes sense.

**Comment by denco** [comment]
Hi, i don't understand why U document how-to associate a file extensions to language ID's? 
Association of Language ID is [well documented by Microsoft](https://code.visualstudio.com/docs/languages/overview#_language-id).

Registered file extensions described in Plug In Contributions Tab. 
file_extensions

For the new ("Untitled") Files U can define a language id in right bottom corner (default is "Plain Text") narrow to "microsoft smile". 
select_langid


Another way is to press  "Ctrl+K M" or what ever... after a Language is defined. VS Code will suggest a registered file extension for this Language ID. 
change_language

So It's pretty simple to do the things in the right way... ;)

**Comment by eponymz** [comment]
I added this to your README because that is where people go for information about your project. Not to the contributions tab of another application. The purpose of a README is to make it simple for users to find configuration details. The file extensions you mentioned in your first comment are not standard top VSCode and therefore this would be the first logical place to look when getting your extension configured within VSCode.

**Comment by denco** [comment]
The point is all of U configuration, except `.mu` Files is already associated with confluence plugin. U have right peoples read a README to get information of the project, but they should read other information too... Such as what is contribution of plugin... 

Sorry but I will reject U pull request and I will close this Topic. Thank U for the providing this Fix, but I see it as useless.

U are welcome to cowork for other issues or feature request, but in a right way: 
1. create an issue for the problem or feature request
1. create a fix
1. create pull request.

NOTE: All of this screenshots taked from VSCode Application
1. extension view of `Confluence markup` Plugin,
1. main window
1. keyboard shortcuts

**Pull request closed without merging**
